name: Check PR for fix_ feature_ release_

on:
  pull_request:
    branches:
      - 'fix_*'
      - 'feature_*'
      - 'release_*'  
    types:
      - closed

jobs:
  lint-code:
    uses: ./.github/workflows/lint-fe.yml

  back-end_test-and-coverage:
    uses: ./.github/workflows/test-coverage-be.yml

  check-fix-feature-release:
    runs-on: ubuntu-22.04
    needs:
      - lint-code
      - back-end_test-and-coverage

    steps:
      - name: Reuse lint-code and back-end_test-and-coverage
        run: | 
          echo "Ok"
          exit 0