name: Lint for front

on:
  push:
    branches:
      - "fe_fix_*"
      - "fe_feature_*"
      - "fe_release_*"

jobs:
  lint-code:
    runs-on: ubuntu-22.04

    steps:
      - name: Change directory to client and install dependencies
        run: |
          cd client
          pwd
          npm install
      - name: Run lint
        run: npm run lint
        working-directory: client
